"""added new exp type for sc data

Revision ID: 6598ad9a7f33
Revises: 2a1081245758
Create Date: 2019-10-04 15:40:18.564687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6598ad9a7f33'
down_revision = '2a1081245758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
