"""updates for exp metadata v2

Revision ID: e776f8bcea2c
Revises: 4289e0e8d201
Create Date: 2019-11-22 13:14:48.541042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e776f8bcea2c'
down_revision = '4289e0e8d201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'WITHDRAWN'), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
