channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.9
  - pip
  - pandas==1.1.0
  - pip:
    - coveralls==1.3.0
    - paramiko==2.7.1
    - html5lib==1.0.1
    - lxml==4.2.4
    - bs4==0.0.1
    - SQLAlchemy==1.3.18
    - PyMySQL==0.9.2
    - slackclient==1.3.2
    - asana==0.8.0
    - matplotlib==2.2.3
    - unittest2==1.1.0
    - Jinja2==2.11.2
    - gviz-api==1.9.0
    - xlrd==1.1.0
    - jsonschema==3.2.0
    - sphinx_rtd_theme==0.4.3
    - spython==0.0.85
