"""added nova to exp table

Revision ID: 442ba214cfa3
Revises: 4d320ef483f9
Create Date: 2021-09-08 18:11:43.955501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '442ba214cfa3'
down_revision = '4d320ef483f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('igf_id_UNIQUE', table_name='rejected_run')
    op.drop_table('rejected_run')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_run',
    sa.Column('run_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('igf_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('date_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('run_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('igf_id_UNIQUE', 'rejected_run', ['igf_id'], unique=True)
    # ### end Alembic commands ###
