"""adding cosmx tables

Revision ID: 8624ea7f09cc
Revises: 6192847ca318
Create Date: 2025-08-27 14:47:12.322302

"""
import igf_data
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8624ea7f09cc'
down_revision = '6192847ca318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosmx_platform',
    sa.Column('cosmx_platform_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cosmx_platform_igf_id', sa.String(length=20), nullable=False),
    sa.Column('cosmx_platform_name', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('cosmx_platform_id'),
    sa.UniqueConstraint('cosmx_platform_igf_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cosmx_run',
    sa.Column('cosmx_run_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cosmx_run_igf_id', sa.String(length=200), nullable=False),
    sa.Column('cosmx_run_name', sa.String(length=100), nullable=True),
    sa.Column('project_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cosmx_run_id'),
    sa.UniqueConstraint('cosmx_run_igf_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cosmx_slide',
    sa.Column('cosmx_slide_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cosmx_slide_igf_id', sa.String(length=100), nullable=False),
    sa.Column('cosmx_slide_name', sa.String(length=100), nullable=True),
    sa.Column('cosmx_run_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cosmx_platform_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('panel_info', sa.String(length=100), nullable=True),
    sa.Column('assay_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('slide_run_date', sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('slide_metadata', igf_data.igfdb.datatype.JSONType(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cosmx_platform_id'], ['cosmx_platform.cosmx_platform_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cosmx_run_id'], ['cosmx_run.cosmx_run_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cosmx_slide_id'),
    sa.UniqueConstraint('cosmx_slide_igf_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cosmx_fov',
    sa.Column('cosmx_fov_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cosmx_fov_name', sa.String(length=10), nullable=False),
    sa.Column('cosmx_slide_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('slide_type', sa.Enum('RNA', 'PROTEIN', 'UNKNOWN'), server_default='UNKNOWN', nullable=False),
    sa.ForeignKeyConstraint(['cosmx_slide_id'], ['cosmx_slide.cosmx_slide_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cosmx_fov_id'),
    sa.UniqueConstraint('cosmx_fov_name', 'cosmx_slide_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cosmx_slide_attribute',
    sa.Column('cosmx_slide_attribute_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('attribute_name', sa.String(length=200), nullable=False),
    sa.Column('attribute_value', igf_data.igfdb.datatype.JSONType(), nullable=True),
    sa.Column('cosmx_slide_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['cosmx_slide_id'], ['cosmx_slide.cosmx_slide_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cosmx_slide_attribute_id'),
    sa.UniqueConstraint('cosmx_slide_id', 'attribute_name'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cosmx_fov_annotation',
    sa.Column('cosmx_fov_annotation_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cosmx_fov_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('tissue_species', sa.Enum('HUMAN', 'MOUSE', 'UNKNOWN'), server_default='UNKNOWN', nullable=False),
    sa.Column('tissue_annotation', sa.String(length=100), nullable=True),
    sa.Column('tissue_ontology', sa.String(length=100), nullable=True),
    sa.Column('tissue_condition', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cosmx_fov_id'], ['cosmx_fov.cosmx_fov_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cosmx_fov_annotation_id'),
    sa.UniqueConstraint('cosmx_fov_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cosmx_fov_attribute',
    sa.Column('cosmx_fov_attribute_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('attribute_name', sa.String(length=200), nullable=False),
    sa.Column('attribute_value', igf_data.igfdb.datatype.JSONType(), nullable=True),
    sa.Column('cosmx_fov_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['cosmx_fov_id'], ['cosmx_fov.cosmx_fov_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cosmx_fov_attribute_id'),
    sa.UniqueConstraint('cosmx_fov_id', 'attribute_name'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cosmx_fov_protein_qc',
    sa.Column('cosmx_fov_protein_qc_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cosmx_fov_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('mean_fluorescence_intensity', mysql.INTEGER(), nullable=True),
    sa.Column('mean_unique_genes_per_cell', mysql.INTEGER(), nullable=True),
    sa.Column('number_non_empty_cells', mysql.INTEGER(), nullable=True),
    sa.Column('pct_non_empty_cells', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.Column('percentile_10_fluorescence_intensity', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.Column('percentile_90_fluorescence_intensity', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.Column('fluorescence_intensity_mean_igg_control_intensity', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.ForeignKeyConstraint(['cosmx_fov_id'], ['cosmx_fov.cosmx_fov_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cosmx_fov_protein_qc_id'),
    sa.UniqueConstraint('cosmx_fov_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cosmx_fov_rna_qc',
    sa.Column('cosmx_fov_rna_qc_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cosmx_fov_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('mean_transcript_per_cell', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.Column('mean_unique_genes_per_cell', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.Column('number_non_empty_cells', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('pct_non_empty_cells', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.Column('percentile_90_transcript_per_cell', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.Column('percentile_10_transcript_per_cell', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.Column('mean_negprobe_counts_per_cell', igf_data.igfdb.datatype.DECIMALType(), nullable=True),
    sa.ForeignKeyConstraint(['cosmx_fov_id'], ['cosmx_fov.cosmx_fov_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cosmx_fov_rna_qc_id'),
    sa.UniqueConstraint('cosmx_fov_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('history')
    op.alter_column('experiment', 'platform_name',
               existing_type=mysql.ENUM('HISEQ2500', 'HISEQ4000', 'MISEQ', 'NEXTSEQ', 'NEXTSEQ2000', 'NOVASEQ6000', 'NANOPORE_MINION', 'DNBSEQ-G400', 'DNBSEQ-G50', 'DNBSEQ-T7', 'SEQUEL2', 'UNKNOWN'),
               type_=sa.Enum('HISEQ2500', 'HISEQ4000', 'MISEQ', 'NEXTSEQ', 'NANOPORE_MINION', 'NOVASEQ6000', 'DNBSEQ-G400', 'DNBSEQ-G50', 'DNBSEQ-T7', 'NEXTSEQ2000', 'SEQUEL2', 'UNKNOWN'),
               existing_nullable=False,
               existing_server_default=sa.text("'UNKNOWN'"))
    op.alter_column('pipeline', 'pipeline_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('pipeline_seed', 'seed_table',
               existing_type=mysql.ENUM('project', 'sample', 'experiment', 'run', 'file', 'seqrun', 'collection', 'analysis', 'unknown'),
               type_=sa.Enum('project', 'sample', 'experiment', 'run', 'file', 'seqrun', 'analysis', 'collection', 'unknown'),
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'"))
    op.alter_column('project', 'project_igf_id',
               existing_type=mysql.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'email_id',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.drop_index('name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'user', ['name'], unique=True)
    op.alter_column('user', 'email_id',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('project', 'project_igf_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('pipeline_seed', 'seed_table',
               existing_type=sa.Enum('project', 'sample', 'experiment', 'run', 'file', 'seqrun', 'analysis', 'collection', 'unknown'),
               type_=mysql.ENUM('project', 'sample', 'experiment', 'run', 'file', 'seqrun', 'collection', 'analysis', 'unknown'),
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'"))
    op.alter_column('pipeline', 'pipeline_name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('experiment', 'platform_name',
               existing_type=sa.Enum('HISEQ2500', 'HISEQ4000', 'MISEQ', 'NEXTSEQ', 'NANOPORE_MINION', 'NOVASEQ6000', 'DNBSEQ-G400', 'DNBSEQ-G50', 'DNBSEQ-T7', 'NEXTSEQ2000', 'SEQUEL2', 'UNKNOWN'),
               type_=mysql.ENUM('HISEQ2500', 'HISEQ4000', 'MISEQ', 'NEXTSEQ', 'NEXTSEQ2000', 'NOVASEQ6000', 'NANOPORE_MINION', 'DNBSEQ-G400', 'DNBSEQ-G50', 'DNBSEQ-T7', 'SEQUEL2', 'UNKNOWN'),
               existing_nullable=False,
               existing_server_default=sa.text("'UNKNOWN'"))
    op.create_table('history',
    sa.Column('log_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('log_type', mysql.ENUM('CREATED', 'MODIFIED', 'DELETED'), nullable=False),
    sa.Column('table_name', mysql.ENUM('PROJECT', 'USER', 'SAMPLE', 'EXPERIMENT', 'RUN', 'COLLECTION', 'FILE', 'PLATFORM', 'PROJECT_ATTRIBUTE', 'EXPERIMENT_ATTRIBUTE', 'COLLECTION_ATTRIBUTE', 'SAMPLE_ATTRIBUTE', 'RUN_ATTRIBUTE', 'FILE_ATTRIBUTE'), nullable=False),
    sa.Column('log_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('cosmx_fov_rna_qc')
    op.drop_table('cosmx_fov_protein_qc')
    op.drop_table('cosmx_fov_attribute')
    op.drop_table('cosmx_fov_annotation')
    op.drop_table('cosmx_slide_attribute')
    op.drop_table('cosmx_fov')
    op.drop_table('cosmx_slide')
    op.drop_table('cosmx_run')
    op.drop_table('cosmx_platform')
    # ### end Alembic commands ###
