"""updateding exp table

Revision ID: a9afd3bafe6f
Revises: e8db5fecec16
Create Date: 2022-05-09 13:22:34.436491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9afd3bafe6f'
down_revision = 'e8db5fecec16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
