"""adding new platforms

Revision ID: e8db5fecec16
Revises: 442ba214cfa3
Create Date: 2022-05-05 15:03:29.228635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8db5fecec16'
down_revision = '442ba214cfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
